### ISSUE TITLE
Add support for automatically patching LBP1 for RPCS3

### ISSUE THREAD

**Issue by CommandGenius** [LBPUnion/UnionPatcher#12]
Essentially the problem is that RPCS3 doesn't have some certain function implemented that LBP1 calls on boot, which crashes RPCS3. Personally I think this is more of an RPCS3 issue but if we are adding this I would like to have the patcher automatically check for the presence of this function call and remove it if present so we don't have an extra UI element to mess with (which makes things even more complicated in the context of UnionRemotePatcher).

**Comment by AShifter** [comment]
> uhh basically some function doesn't have support for rpcs3 or something idk im half-asleep this basically tries to make it automatically patch it by a checkbox idk

Essentially the problem is that RPCS3 doesn't have some certain function implemented that LBP1 calls on boot, which crashes RPCS3. Personally I think this is more of an RPCS3 issue but if we are adding this I would like to have the patcher automatically check for the presence of this function call and remove it if present so we don't have an extra UI element to mess with (which makes things even more complicated in the context of UnionRemotePatcher).

**Comment by AShifter** [comment]
Debating whether or not to go forward with this issue. This sounds more like RPCS3's issue, I think we should tell them to handle this error properly. This doesn't affect real hardware.
